import React from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import './dist/global-styles.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} id="root">
        <header className="header">
          <Link href={'/'}><img src='/assets/GANBATTE.svg'/></Link>
        </header>
        <div><img src='/assets/Sream-de-Animes-3.jpg' className="banner_img" /></div>

        {children}
      <footer className="footer"><p>Desenvolvido com ❤️ por <a href="https://github.com/rebecaCanesin">Rebeca Canesin</a></p></footer>
      </body>
    </html>
  );
}
